In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv('/home/iitm/Desktop/MLP-prac/Week1_GA_dataset.csv')

In [2]:
df_new=df.copy()

In [3]:
df.head()

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East

How many unknown ("?) values are present in the dataset? Remove/Delete unknown ("?) values present in the dataset to make it null value.
Remove/Delete - means it will show NAN in place of "?"
Note: If there is no value present in the dataset it is represented as NAN(read pandas documentation for all the other ways to represent null values) in data

In [4]:
df.isna().sum()

Date                    0
Year                    0
Locality             1253
Estimated Value      1243
Sale Price              0
Property                0
Residential             0
num_rooms               0
num_bathrooms           0
carpet_area          1229
property_tax_rate       0
Face                    0
dtype: int64

In [5]:
(df=="?").sum()

Date                    0
Year                    0
Locality                0
Estimated Value         0
Sale Price              0
Property             1823
Residential             0
num_rooms               0
num_bathrooms           0
carpet_area             0
property_tax_rate       0
Face                    0
dtype: int64

In [6]:
# Replace all "?" values with NaN
df = df.replace('?', np.nan)
(df=="?").sum()

Date                 0
Year                 0
Locality             0
Estimated Value      0
Sale Price           0
Property             0
Residential          0
num_rooms            0
num_bathrooms        0
carpet_area          0
property_tax_rate    0
Face                 0
dtype: int64

`What is the shape of the dataset ?`

In [7]:
df.shape

(10000, 12)

`What is the value present at the 692th indexed row and 0th indexed column in the data ?`

- dataframe[692,0] (simpy saying this in a matrix)
- rows/ columns starts indexing from zero(0) in python

In [8]:
df.iloc[692,0]

'2009-11-16'

`What is the value present at the 546th indexed row and 7th indexed column in the data ?`

In [9]:
df.iloc[546,7]

np.int64(3)

`What are the unique values present in the Locality feature of the dataset? `

In [10]:
df['Locality'].unique()

array(['Waterbury', 'Bridgeport', 'Greenwich', 'Norwalk', nan,
       'Fairfield', 'West Hartford', 'Stamford'], dtype=object)

In [11]:
df['Locality']

0        Waterbury
1       Bridgeport
2        Waterbury
3       Bridgeport
4       Bridgeport
           ...
9995    Bridgeport
9996    Bridgeport
9997     Waterbury
9998           NaN
9999       Norwalk
Name: Locality, Length: 10000, dtype: object

`Which of the following features have missing(NaN) values present in the dataset?`

`Which of the following feature has most missing(NaN) values present in the dataset?`

In [12]:
df.isnull().sum()

Date                    0
Year                    0
Locality             1253
Estimated Value      1243
Sale Price              0
Property             1823
Residential             0
num_rooms               0
num_bathrooms           0
carpet_area          1229
property_tax_rate       0
Face                    0
dtype: int64

`Drop all the samples(rows) with missing values strictly greater than 2. How many samples remains after that ?`

In [13]:
df[df.isna().sum(axis=1) <= 2]

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,NaN,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,NaN,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,NaN,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [42]:
df.dropna().shape

(5449, 12)

`Select all the even indexed rows from the given dataset. What is the value in the 3rd indexed column of the 0th indexed row in the selected dataframe. (row/ column indexed from zero(0) in python/pandas)`

In [15]:
print(df_new.iloc[::2].iloc[0,3])

111440.0

In [16]:
df_new.iloc[::2]

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East
6,2009-01-02,2009,Norwalk,571060.0,1000000.0,Single Family,Detached House,3,2,NaN,1.025953,South
8,2009-01-02,2009,NaN,603540.0,1680000.0,Single Family,Detached House,3,1,1039.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9990,2022-09-30,2022,NaN,352030.0,700000.0,?,Detached House,3,3,958.0,1.003979,North
9992,2022-09-30,2022,Fairfield,NaN,680000.0,Single Family,Detached House,3,2,908.0,1.003979,West
9994,2022-09-30,2022,NaN,155550.0,215000.0,Three Family,Triplex,6,5,2114.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,?,Duplex,4,4,1416.0,1.003979,North
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North

`Select all the even indexed rows from the given dataset. What is the value in the 3rd indexed column of the 332th indexed row in the selected dataframe. (row/ column indexed from zero(0)) `

In [44]:
print(df_new.iloc[::2].iloc[332,3])

256200.0

`Select all the odd indexed rows from the given dataset. What is the value in the 3rd indexed column of the 332th indexed row in the selected dataframe. (row/ column indexed from zero(0))`

In [18]:
print(df_new.iloc[1::2].iloc[332,3])

352940.0

`Select all the odd indexed columns from the given dataset. What is the value in the 5th indexed column of the 100th indexed row in the selected dataframe. (row/ column indexed from zero(0)) `

In [19]:
print(df_new.iloc[:,1::2].iloc[100,5])

West

`Select all the even indexed columns and even indexed rows from the given dataset. What is the value in the 3th indexed column of the 255th indexed row in the selected dataframe. (row/ column indexed/starts from zero(0)) `

In [20]:
print(df_new.iloc[:,0::2].iloc[255,3])

Detached House

`Determine the number of samples (rows) in the dataset that belong to the six most recent years, `

In [21]:
df['Year'].value_counts().sort_index(ascending=False).iloc[:6].sum()

np.int64(4749)

`Determine the number of samples (rows) in the dataset which has num_rooms = 3 and num_bathrooms = 3`

In [22]:
((df['num_rooms']==3) & (df['num_bathrooms']==3) ).sum()

np.int64(2730)

In [23]:
df[(df['num_rooms']==3) & (df['num_bathrooms']==3)].shape

(2730, 12)

`Determine the number of samples (rows) in the dataset which has num_rooms = 3 or num_bathrooms = 3`

In [24]:
(df[(df['num_rooms']==3) | (df['num_bathrooms']==3)]).shape

(8591, 12)

`In the Year 2022, how many houses (rows) located in the Greenwich Locality have exactly num_room == 3, and facing towards either the North or East?`

In [25]:
df[(df['Year']==2022)&(df['Locality']=='Greenwich') &(df['num_rooms']==3)& ( (df['Face']=='North') |(df['Face']=='East') ) ].shape

(42, 12)

`Calculate the number of samples(rows) that correspond to the month of August across all the years.?`

In [38]:
date=0
for i in df['Date']:
    dt=i.split('-')
    if dt[1]=='10':
        date+=1
print(date)

784

`According to the data which Locality have highest average Sale Price?`

In [27]:
df.loc[:,['Locality','Sale Price']]

        Locality  Sale Price
0      Waterbury    185000.0
1     Bridgeport    150000.0
2      Waterbury    140000.0
3     Bridgeport    272900.0
4     Bridgeport    210000.0
...          ...         ...
9995  Bridgeport    322000.0
9996  Bridgeport    340000.0
9997   Waterbury    170000.0
9998         NaN    415000.0
9999     Norwalk    196000.0

[10000 rows x 2 columns]

In [36]:
df.groupby('Locality')['Sale Price'].mean()

Locality
Bridgeport       1.740953e+05
Fairfield        7.277225e+05
Greenwich        2.270224e+06
Norwalk          5.590959e+05
Stamford         6.305313e+05
Waterbury        1.062152e+05
West Hartford    3.385472e+05
Name: Sale Price, dtype: float64